=== hathitrust/ht_schemas/fulltext_schemas/each_document.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "FullTextItem",
  "type": "object",
  "$id": "https://hathitrust.org/fulltext_schemas/each_document.json",
  "_comment": "uniqueItems is set to true to ensure that there are no duplicate items in the array. The minItems is set to 1 to ensure that there is at least one item in the array.",
  "properties": {
    "bookID": {
      "description": "The unique OCLC number for each record. In the front-end, the field is bookID.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "minItems": 1
    },
    "title": {
      "description": "The title of the item. Title is the field name in the front-end.",
      "type": "string"
    },
    "itemID": {
      "description": "The unique ht_id number. In the front-end this is the field name ItemID.",
      "type": "string"
    },
    "record": {
      "description": "Catalog record ID",
      "type": "string"
    },
    "author": {
      "description": "The author of the item. In the front-end, this is the field name Author.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "minItems": 1
    },
    "useDate": {
      "description": "Calculated field from the Solr fields bothPublishDate and date. In the front-end, this is the field name UseDate.",
      "type": "integer"
    },
    "date": {
      "description": "date Solr field of the item. In the front-end, this is the field name Date.",
      "type": "integer"
    },
    "enumDate": {
      "description": "First date in the Solr field enumPublishDate. In the front-end, this is the field name EnumDate.",
      "type": "integer"
    },
    "bothDate": {
      "description": "First date in the Solr field bothPublishDate. In the front-end, this is the field name BothDate.",
      "type": "integer"
    },
    "abLabel": {
      "description": "Label obtained by interleave. In the front-end, this is the field name ABLabel.",
      "type": "string"
    },
    "result_number": {
      "description": "Position of each item in the list of results. In the front-end, this is the field name ResultNumber.",
      "type": "integer"
    },
    "relevance": {
      "description": "Solr query score value. In the front-end, this is the field name relevance.",
      "type": "number"
    },
    "rights": {
      "description": "Rights field from Solr. In the front-end, this is the field name rights.",
      "type": "integer"
    },
    "fulltext": {
      "description": "Flag indicating the item access status. In the front-end, this is the field name fulltext.",
      "enum": [
        0,
        1
      ]
    },
    "emergency": {
      "description": "Flag indicating the emergency_flag is access_status is allow. In the front-end, this is the field name emergency.",
      "enum": [
        0,
        1
      ]
    },
    "key": {
      "description": "Calculated flag according emergency and fulltext flag. In the front-end this is the field name Key.",
      "enum": [
        "limited",
        "emergency",
        "fulltext",
        "fulltext_activated"
      ]
    },
    "ptSearchHref": {
      "description": "URL to the item in Pageturner search. In the front-end, this is the field name PtSearchHref.",
      "type": "string"
    },
    "ptHref": {
      "description": "URL to the item in Pageturner. In the front-end, this is the field name PtHref.",
      "type": "string"
    }
  },
  "required": [
    "title",
    "itemID",
    "record",
    "rights",
    "fulltext",
    "emergency",
    "key",
    "ptSearchHref",
    "ptHref"
  ]
}

=== hathitrust/ht_schemas/fulltext_json/each_document.json
{
  "itemID": "chi.29215625",
  "title": "The Anglo Irish",
  "record": "100859789",
  "author": ["Banim, John, 1798-1842"],
  "useDate": 1838,
  "date": 1838,
  "enumDate": 1838,
  "bothDate": 1838,
  "rights": 1,
  "fulltext": 1,
  "emergency": 0,
  "key": "limited",
  "ptSearchHref": "/cgi/pt/search?id=uc1.b4809968;debug=xml;",
  "ptHref": "/cgi/pt?id=uc1.b4809968;debug=xml;"
}
